version: "3.9"

networks:
  default:
    name: traefik_net
    external: true

# ##########################################
services:

  blog:
    container_name: dagblogweb
    image: cr.dag.lan/dagblog-web:latest
    restart: unless-stopped
    environment:
      MODE: STAGING
      TZ: Europe/Rome
    links:
      - php
    depends_on:
      - php
    volumes:
      - ./assets:/app/assets # collegamento ai file statici
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dagblog.rule=Host(`blog.dag.lan`) && (PathPrefix(`/blog`) || Path(`/`))"
      - "traefik.http.routers.dagblog.entrypoints=websecure"
      - "traefik.http.routers.dagblog.tls=true"
      # - "traefik.http.routers.dagblog.tls.certresolver=le"
      - "traefik.http.middlewares.dagblog_redirect.redirectregex.regex=^https:\\/\\/(blog\\.dag\\.lan)\\/?$$"
      - "traefik.http.middlewares.dagblog_redirect.redirectregex.replacement=https://blog.dag.lan/blog"
      - "traefik.http.routers.dagblog.middlewares=dagblog_redirect@docker"    

  php:
    container_name: dagblogphp
    image: cr.dag.lan/dagblog-php:latest
    restart: unless-stopped
    volumes:
      - ./assets:/app/assets # collegamento ai file statici
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MODE: STAGING
      TZ: Europe/Rome
    networks:
      - default

#   api:
#     container_name: dagblogapi
#     build:
#       context: ./
#       dockerfile: Dockerfile.prod-api
#     restart: unless-stopped
#     environment:
#       MODE: DEVELOPMENT
#       PYTHONUNBUFFERED: 1
#       TZ: Europe/Rome
#     volumes:
#       # - ./api:/app # cartella dell'applicazione
#       - ./assets:/app/assets # cartella per lo storage dei file statici
#       - instagram_media:/app/assets/images/ig/download
#       - ./secrets/ig_tokens:/app/lib/data/ig_tokens
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     networks:
#       - default
#     secrets:
#       - mail_pw
#       - contact_addresses
#       - ig_user_id
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.dagblogapi.rule=Host(`simo.dag.lan`) && PathPrefix(`/api`) "
#       - "traefik.http.routers.dagblogapi.entrypoints=websecure"
#       - "traefik.http.routers.dagblogapi.tls=true"
#       # - "traefik.http.routers.dagblogapi.tls.certresolver=le"
#       - "traefik.http.routers.dagblogapi.middlewares=api_stripprefix@docker"
#       - "traefik.http.middlewares.api_stripprefix.stripprefix.prefixes=/api"


#   cron:
#     container_name: simocron
#     build:
#       context: ./
#       dockerfile: Dockerfile.prod-cron
#     restart: unless-stopped
#     environment:
#       PYTHONUNBUFFERED: 1
#       IG_CHECK_FREQ: 600 # secondi di frequenza del controllo del loop
#       IG_RENEW_FREQ: 3600 # secondi di frequenza di rinnovo dei media e del token
#       TZ: Europe/Rome
#       MODE: DEVELOPMENT
#     volumes:
#       # - ./api:/app # cartella dell'applicazione
#       - ./assets:/app/assets # cartella per lo storage dei file statici
#       - ./secrets/ig_tokens:/app/lib/data/ig_tokens
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     networks:
#       - default
#     secrets:
#       - mail_pw
#       - contact_addresses
#       - ig_user_id
