version: "3.9"

networks:
  blognet:

##########################################
# secrets:
#   contact_addresses:
#     file: secrets/contact_addresses
#   mail_pw:
#     file: secrets/mail_pw
#   ig_user_id:
#     file: secrets/ig_user_id

##########################################
volumes:
  blog:
    name: blog

##########################################
services:

  blog:
    container_name: dagblogweb
    image: nginx
    restart: unless-stopped
    ports:
      - 8710:80
    environment:
      MODE: DEVELOPMENT
      TZ: Europe/Rome
    links:
      - php
    depends_on:
      - php
    volumes:
      - ./web:/app # cartella del sito
      - ./assets:/app/assets # collegamento ai file statici
      - ./config/nginx/web.conf:/etc/nginx/conf.d/default.conf
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - blognet

  php:
    container_name: dagblogphp
    image: php:8-fpm-bullseye
    volumes:
      - ./web:/app
      - ./assets:/app/assets # collegamento ai file statici
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    environment:
      MODE: DEVELOPMENT
      TZ: Europe/Rome
    networks:
      - blognet

  # api:
  #   container_name: simoapi
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.dev-api
  #   restart: unless-stopped
  #   environment:
  #     MODE: DEVELOPMENT
  #     PYTHONUNBUFFERED: 1
  #     TZ: Europe/Rome
  #   ports:
  #     - 8220:8000
  #   volumes:
  #     - ./api:/app # cartella dell'applicazione
  #     - ./assets:/app/assets # cartella per lo storage dei file statici
  #     - instagram_media:/app/assets/images/ig/download
  #     - ./secrets/ig_tokens:/app/lib/data/ig_tokens
  #     # - /etc/timezone:/etc/timezone:ro
  #     # - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     - simonet1
  #   secrets:
  #     - mail_pw
  #     - contact_addresses
  #     - ig_user_id


  # admin:
  #   container_name: blog_admin
  #   image: nginx
  #   restar: unless_stopped
  #   ports:
  #     - 8710:80
  #   # depends_on:
  #   #   - db
  #   # volumes:
  #   #   - /etc/timezone:/etc/timezone:ro
  #   #   - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     - blognet