# FROM python:3.10
# WORKDIR /app
# EXPOSE 8000
# COPY ./api/requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt

# CMD [ "python", "-u",  "./main.py" ]
# # la -u è per mostrare i print nel log (UNBUFFERED=1)
# #