version: "3.9"

networks:
  default:
    name: traefik_net
    external: true

# ##########################################
services:

  blog:
    container_name: dagblogweb
    image: ghcr.io/ildug/dagblog-web
    restart: unless-stopped
    environment:
      MODE: PRODUCTION
      TZ: Europe/Rome
    links:
      - php
    depends_on:
      - php
    volumes:
      - ./assets:/app/assets # collegamento ai file statici
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dagbog.rule=Host(`blog.dagtech.it`)"
      - "traefik.http.routers.dagbog.entrypoints=websecure"
      - "traefik.http.routers.dagbog.tls=true"
      - "traefik.http.routers.dagbog.tls.certresolver=le"

  php:
    container_name: dagblogphp
    image: ghcr.io/ildug/dagblog-php
    restart: unless-stopped
    volumes:
      - ./assets:/app/assets # collegamento ai file statici
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MODE: PRODUCTION
      TZ: Europe/Rome
    networks:
      - default

#   api:
#     container_name: dagblogapi
#     image: ghcr.io/ildug/simounichecreazioni-api
#     restart: unless-stopped
#     environment:
#       MODE: PRODUCTION # ${MODE:-PRODUCTION}
#       PYTHONUNBUFFERED: 1
#       TZ: Europe/Rome
#     volumes:
#       - ./assets:/app/assets # cartella per lo storage dei file statici
#       - instagram_media:/app/assets/images/ig/download
#       - ./secrets/ig_tokens:/app/lib/data/ig_tokens
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     networks:
#       - default
#     secrets:
#       - mail_pw
#       - contact_addresses
#       - ig_user_id
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.dagblogapi.rule=Host(`simounichecreazioni.it`) && PathPrefix(`/api`) "
#       - "traefik.http.routers.dagblogapi.entrypoints=websecure"
#       - "traefik.http.routers.dagblogapi.tls=true"
#       - "traefik.http.routers.dagblogapi.tls.certresolver=le"
#       - "traefik.http.routers.dagblogapi.middlewares=api_stripprefix@docker"
#       - "traefik.http.middlewares.api_stripprefix.stripprefix.prefixes=/api"

#   cron:
#     container_name: simocron
#     image: ghcr.io/ildug/simounichecreazioni-cron
#     restart: unless-stopped
#     environment:
#       MODE: PRODUCTION
#       PYTHONUNBUFFERED: 1
#       IG_CHECK_FREQ: 600 # secondi di frequenza del controllo del loop
#       IG_RENEW_FREQ: 43200 # secondi di frequenza di rinnovo dei media e del token
#       TZ: Europe/Rome
#     volumes:
#       - ./assets:/app/assets # cartella per lo storage dei file statici
#       - ./secrets/ig_tokens:/app/lib/data/ig_tokens
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     networks:
#       - default
#     secrets:
#       - mail_pw
#       - contact_addresses
#       - ig_user_id
